"""client sections

Revision ID: 09ada4bbd42e
Revises: b1c2d3e4f5a6
Create Date: 2026-08-07 14:08:24.725273

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "09ada4bbd42e"
down_revision: str | None = "b1c2d3e4f5a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("contact_person", sa.String(length=255), nullable=False),
        sa.Column("email_id", sa.String(length=255), nullable=True),
        sa.Column("designation", sa.String(length=150), nullable=True),
        sa.Column("office_number", sa.String(length=50), nullable=True),
        sa.Column("mobile_number", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_accounts_client_id"), "client_accounts", ["client_id"], unique=False)
    op.create_table(
        "client_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assignment_role", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "user_id", name="uq_client_assignment_user"),
    )
    op.create_index(op.f("ix_client_assignments_client_id"), "client_assignments", ["client_id"], unique=False)
    op.create_index(op.f("ix_client_assignments_user_id"), "client_assignments", ["user_id"], unique=False)
    op.create_table(
        "client_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_documents_client_id"), "client_documents", ["client_id"], unique=False)
    op.create_table(
        "client_notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("note_type", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_notes_client_id"), "client_notes", ["client_id"], unique=False)
    op.add_column(
        "client_contacts", sa.Column("status", sa.String(length=20), nullable=False, server_default=sa.text("'Active'"))
    )
    op.add_column("clients", sa.Column("short_name", sa.String(length=100), nullable=True))
    op.add_column("clients", sa.Column("vms_client_name", sa.String(length=255), nullable=True))
    op.add_column("clients", sa.Column("federal_id", sa.String(length=50), nullable=True))
    op.add_column("clients", sa.Column("email_id", sa.String(length=255), nullable=True))
    op.add_column("clients", sa.Column("fax", sa.String(length=50), nullable=True))
    op.add_column("clients", sa.Column("practice", sa.String(length=100), nullable=True))
    op.add_column("clients", sa.Column("payment_terms", sa.String(length=50), nullable=True))
    op.add_column("clients", sa.Column("about_company", sa.Text(), nullable=True))
    op.add_column("clients", sa.Column("address", sa.String(length=500), nullable=True))
    op.add_column("clients", sa.Column("city", sa.String(length=100), nullable=True))
    op.add_column("clients", sa.Column("state", sa.String(length=100), nullable=True))
    op.add_column("clients", sa.Column("country", sa.String(length=100), nullable=True))
    op.add_column("clients", sa.Column("postal_code", sa.String(length=20), nullable=True))
    op.add_column(
        "clients",
        sa.Column("client_visibility", sa.String(length=30), nullable=False, server_default=sa.text("'Organization Level'")),
    )
    op.add_column("clients", sa.Column("ownership_id", sa.UUID(), nullable=True))
    op.add_column("clients", sa.Column("client_lead_id", sa.UUID(), nullable=True))
    op.add_column("clients", sa.Column("parent_client_id", sa.UUID(), nullable=True))
    op.add_column("clients", sa.Column("send_requirement", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column("clients", sa.Column("send_hotlist", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column("clients", sa.Column("allow_access_to_all_users", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column(
        "clients", sa.Column("notify_near_client_location", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        "clients", sa.Column("stop_contact_email_on_submit", sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column("clients", sa.Column("default_address_for_jobs", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column(
        "clients",
        sa.Column("client_facilities", postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'")),
    )
    op.add_column(
        "clients",
        sa.Column("required_documents", postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'")),
    )
    op.add_column(
        "clients",
        sa.Column("submission_format_fields", postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'")),
    )
    op.add_column("clients", sa.Column("guidelines", sa.Text(), nullable=True))
    op.add_column("clients", sa.Column("markup_percentage", sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column("clients", sa.Column("overtime_markup_percentage", sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column("clients", sa.Column("standard_working_hours", sa.Integer(), nullable=True))
    op.add_column("clients", sa.Column("submission_instructions", sa.Text(), nullable=True))
    op.create_foreign_key(None, "clients", "clients", ["parent_client_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "clients", "users", ["ownership_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "clients", "users", ["client_lead_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "clients", type_="foreignkey")
    op.drop_constraint(None, "clients", type_="foreignkey")
    op.drop_constraint(None, "clients", type_="foreignkey")
    op.drop_column("clients", "submission_instructions")
    op.drop_column("clients", "standard_working_hours")
    op.drop_column("clients", "overtime_markup_percentage")
    op.drop_column("clients", "markup_percentage")
    op.drop_column("clients", "guidelines")
    op.drop_column("clients", "submission_format_fields")
    op.drop_column("clients", "required_documents")
    op.drop_column("clients", "client_facilities")
    op.drop_column("clients", "default_address_for_jobs")
    op.drop_column("clients", "stop_contact_email_on_submit")
    op.drop_column("clients", "notify_near_client_location")
    op.drop_column("clients", "allow_access_to_all_users")
    op.drop_column("clients", "send_hotlist")
    op.drop_column("clients", "send_requirement")
    op.drop_column("clients", "parent_client_id")
    op.drop_column("clients", "client_lead_id")
    op.drop_column("clients", "ownership_id")
    op.drop_column("clients", "client_visibility")
    op.drop_column("clients", "postal_code")
    op.drop_column("clients", "country")
    op.drop_column("clients", "state")
    op.drop_column("clients", "city")
    op.drop_column("clients", "address")
    op.drop_column("clients", "about_company")
    op.drop_column("clients", "payment_terms")
    op.drop_column("clients", "practice")
    op.drop_column("clients", "fax")
    op.drop_column("clients", "email_id")
    op.drop_column("clients", "federal_id")
    op.drop_column("clients", "vms_client_name")
    op.drop_column("clients", "short_name")
    op.drop_column("client_contacts", "status")
    op.drop_index(op.f("ix_client_notes_client_id"), table_name="client_notes")
    op.drop_table("client_notes")
    op.drop_index(op.f("ix_client_documents_client_id"), table_name="client_documents")
    op.drop_table("client_documents")
    op.drop_index(op.f("ix_client_assignments_user_id"), table_name="client_assignments")
    op.drop_index(op.f("ix_client_assignments_client_id"), table_name="client_assignments")
    op.drop_table("client_assignments")
    op.drop_index(op.f("ix_client_accounts_client_id"), table_name="client_accounts")
    op.drop_table("client_accounts")
    # ### end Alembic commands ###
