"""job sections

Revision ID: 1dd771a3fda8
Revises: ca2fcceb76d4
Create Date: 2026-08-07 15:20:28.144437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1dd771a3fda8'
down_revision: Union[str, None] = 'ca2fcceb76d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_custom_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=150), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'field_name', name='uq_job_custom_field_name')
    )
    op.create_index(op.f('ix_job_custom_fields_job_id'), 'job_custom_fields', ['job_id'], unique=False)
    op.create_table('job_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_documents_job_id'), 'job_documents', ['job_id'], unique=False)
    op.create_table('job_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('note_type', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_notes_job_id'), 'job_notes', ['job_id'], unique=False)
    op.create_table('job_search_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('boolean_string', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('recent_job_title_only', sa.Boolean(), nullable=False),
    sa.Column('search_mode', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('radius_miles', sa.Integer(), nullable=True),
    sa.Column('search_radius_within_state', sa.Boolean(), nullable=False),
    sa.Column('include_applicants_without_country', sa.Boolean(), nullable=False),
    sa.Column('experience_min_years', sa.Integer(), nullable=True),
    sa.Column('experience_max_years', sa.Integer(), nullable=True),
    sa.Column('education', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('work_authorizations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('employer', sa.String(length=255), nullable=True),
    sa.Column('most_recent_employer_only', sa.Boolean(), nullable=False),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('clearance', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_search_criteria_job_id'), 'job_search_criteria', ['job_id'], unique=True)
    op.add_column('jobs', sa.Column('business_unit', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('facility', sa.String(length=150), nullable=True))
    op.add_column('jobs', sa.Column('end_client', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('job_status_detail', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('duration', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('required_hours_per_week', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('interview_mode', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('clearance_required', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('jobs', sa.Column('additional_details', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('employment_test_template', sa.String(length=150), nullable=True))
    op.add_column('jobs', sa.Column('employment_level', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('required_documents', postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('jobs', sa.Column('work_authorizations', postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('jobs', sa.Column('respond_by', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('respond_by_date', sa.Date(), nullable=True))
    op.add_column('jobs', sa.Column('turnaround_time_value', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('turnaround_time_unit', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('pay_rate_currency', sa.String(length=10), nullable=False, server_default=sa.text("'USD'")))
    op.add_column('jobs', sa.Column('pay_rate_unit', sa.String(length=20), nullable=False, server_default=sa.text("'Hourly'")))
    op.add_column('jobs', sa.Column('pay_rate_type', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('client_bill_rate_min', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('client_bill_rate_max', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('client_bill_rate_currency', sa.String(length=10), nullable=False, server_default=sa.text("'USD'")))
    op.add_column('jobs', sa.Column('client_bill_rate_unit', sa.String(length=20), nullable=False, server_default=sa.text("'Hourly'")))
    op.add_column('jobs', sa.Column('client_bill_rate_type', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('jobs', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('states', postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('jobs', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('experience_min_years', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('experience_max_years', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('max_allowed_submissions', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('tax_terms', postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('jobs', sa.Column('sales_manager_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('recruitment_manager_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('account_manager_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('primary_recruiter_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('assigned_to_ids', postgresql.ARRAY(sa.UUID()), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('jobs', sa.Column('comments', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'users', ['account_manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'jobs', 'users', ['recruitment_manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'jobs', 'users', ['sales_manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'jobs', 'users', ['primary_recruiter_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'comments')
    op.drop_column('jobs', 'assigned_to_ids')
    op.drop_column('jobs', 'primary_recruiter_id')
    op.drop_column('jobs', 'account_manager_id')
    op.drop_column('jobs', 'recruitment_manager_id')
    op.drop_column('jobs', 'sales_manager_id')
    op.drop_column('jobs', 'tax_terms')
    op.drop_column('jobs', 'max_allowed_submissions')
    op.drop_column('jobs', 'experience_max_years')
    op.drop_column('jobs', 'experience_min_years')
    op.drop_column('jobs', 'postal_code')
    op.drop_column('jobs', 'country')
    op.drop_column('jobs', 'states')
    op.drop_column('jobs', 'city')
    op.drop_column('jobs', 'address')
    op.drop_column('jobs', 'client_bill_rate_type')
    op.drop_column('jobs', 'client_bill_rate_unit')
    op.drop_column('jobs', 'client_bill_rate_currency')
    op.drop_column('jobs', 'client_bill_rate_max')
    op.drop_column('jobs', 'client_bill_rate_min')
    op.drop_column('jobs', 'pay_rate_type')
    op.drop_column('jobs', 'pay_rate_unit')
    op.drop_column('jobs', 'pay_rate_currency')
    op.drop_column('jobs', 'turnaround_time_unit')
    op.drop_column('jobs', 'turnaround_time_value')
    op.drop_column('jobs', 'respond_by_date')
    op.drop_column('jobs', 'respond_by')
    op.drop_column('jobs', 'work_authorizations')
    op.drop_column('jobs', 'required_documents')
    op.drop_column('jobs', 'employment_level')
    op.drop_column('jobs', 'employment_test_template')
    op.drop_column('jobs', 'additional_details')
    op.drop_column('jobs', 'clearance_required')
    op.drop_column('jobs', 'interview_mode')
    op.drop_column('jobs', 'required_hours_per_week')
    op.drop_column('jobs', 'duration')
    op.drop_column('jobs', 'job_status_detail')
    op.drop_column('jobs', 'end_client')
    op.drop_column('jobs', 'facility')
    op.drop_column('jobs', 'business_unit')
    op.drop_index(op.f('ix_job_search_criteria_job_id'), table_name='job_search_criteria')
    op.drop_table('job_search_criteria')
    op.drop_index(op.f('ix_job_notes_job_id'), table_name='job_notes')
    op.drop_table('job_notes')
    op.drop_index(op.f('ix_job_documents_job_id'), table_name='job_documents')
    op.drop_table('job_documents')
    op.drop_index(op.f('ix_job_custom_fields_job_id'), table_name='job_custom_fields')
    op.drop_table('job_custom_fields')
    # ### end Alembic commands ###
