"""phase_4_ai_review

Revision ID: a4af0f56fe06
Revises: 366a7d80019a
Create Date: 2026-07-20 12:21:00.004237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a4af0f56fe06'
down_revision: Union[str, None] = '366a7d80019a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rule_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('semantic_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recommendation_label', sa.String(length=30), nullable=True),
    sa.Column('strengths', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('gaps', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('risk_flags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('matched_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('missing_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('suggested_interview_questions', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'version', name='uq_ai_evaluation_application_version')
    )
    op.create_index(op.f('ix_ai_evaluations_application_id'), 'ai_evaluations', ['application_id'], unique=False)
    op.create_index(op.f('ix_ai_evaluations_organization_id'), 'ai_evaluations', ['organization_id'], unique=False)
    op.create_table('resume_parse_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['candidate_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_parse_runs_candidate_id'), 'resume_parse_runs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resume_parse_runs_document_id'), 'resume_parse_runs', ['document_id'], unique=False)
    op.create_index(op.f('ix_resume_parse_runs_organization_id'), 'resume_parse_runs', ['organization_id'], unique=False)
    op.create_table('ai_evaluation_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('overridden_by', sa.UUID(), nullable=True),
    sa.Column('previous_recommendation', sa.String(length=30), nullable=True),
    sa.Column('new_recommendation', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['ai_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_evaluation_overrides_evaluation_id'), 'ai_evaluation_overrides', ['evaluation_id'], unique=False)
    op.create_table('parsed_resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_parse_run_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('total_experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('work_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_parse_run_id'], ['resume_parse_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_parse_run_id')
    )
    op.create_index(op.f('ix_parsed_resumes_candidate_id'), 'parsed_resumes', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_resumes_candidate_id'), table_name='parsed_resumes')
    op.drop_table('parsed_resumes')
    op.drop_index(op.f('ix_ai_evaluation_overrides_evaluation_id'), table_name='ai_evaluation_overrides')
    op.drop_table('ai_evaluation_overrides')
    op.drop_index(op.f('ix_resume_parse_runs_organization_id'), table_name='resume_parse_runs')
    op.drop_index(op.f('ix_resume_parse_runs_document_id'), table_name='resume_parse_runs')
    op.drop_index(op.f('ix_resume_parse_runs_candidate_id'), table_name='resume_parse_runs')
    op.drop_table('resume_parse_runs')
    op.drop_index(op.f('ix_ai_evaluations_organization_id'), table_name='ai_evaluations')
    op.drop_index(op.f('ix_ai_evaluations_application_id'), table_name='ai_evaluations')
    op.drop_table('ai_evaluations')
    # ### end Alembic commands ###
