"""vendor sections

Revision ID: ca2fcceb76d4
Revises: 09ada4bbd42e
Create Date: 2026-08-07 14:44:06.989485

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "ca2fcceb76d4"
down_revision: str | None = "09ada4bbd42e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("contact_person", sa.String(length=255), nullable=False),
        sa.Column("email_id", sa.String(length=255), nullable=True),
        sa.Column("designation", sa.String(length=150), nullable=True),
        sa.Column("office_number", sa.String(length=50), nullable=True),
        sa.Column("mobile_number", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vendor_accounts_vendor_id"), "vendor_accounts", ["vendor_id"], unique=False)
    op.create_table(
        "vendor_bank_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("account_holder_name", sa.String(length=255), nullable=False),
        sa.Column("bank_name", sa.String(length=255), nullable=False),
        sa.Column("account_number", sa.String(length=50), nullable=False),
        sa.Column("account_type", sa.String(length=30), nullable=True),
        sa.Column("routing_number", sa.String(length=50), nullable=True),
        sa.Column("swift_code", sa.String(length=20), nullable=True),
        sa.Column("branch_address", sa.String(length=500), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vendor_id", "account_number", name="uq_vendor_bank_account_number"),
    )
    op.create_index(op.f("ix_vendor_bank_accounts_vendor_id"), "vendor_bank_accounts", ["vendor_id"], unique=False)
    op.create_table(
        "vendor_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vendor_documents_vendor_id"), "vendor_documents", ["vendor_id"], unique=False)
    op.create_table(
        "vendor_notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("notified_user_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vendor_notes_vendor_id"), "vendor_notes", ["vendor_id"], unique=False)
    op.create_table(
        "vendor_meetings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("meeting_for", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("attendee_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("guest_attendees", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["vendor_contacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vendor_id"], ["vendors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vendor_meetings_vendor_id"), "vendor_meetings", ["vendor_id"], unique=False)
    op.add_column("vendor_contacts", sa.Column("work_phone", sa.String(length=50), nullable=True))
    op.add_column("vendor_contacts", sa.Column("designation", sa.String(length=150), nullable=True))
    op.add_column(
        "vendor_contacts", sa.Column("status", sa.String(length=20), nullable=False, server_default=sa.text("'Active'"))
    )
    op.add_column(
        "vendor_contacts",
        sa.Column("vms_status", sa.String(length=30), nullable=False, server_default=sa.text("'Not Initiated'")),
    )
    op.add_column("vendor_contacts", sa.Column("owner_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "vendor_contacts", "users", ["owner_id"], ["id"], ondelete="SET NULL")
    op.add_column("vendors", sa.Column("federal_id", sa.String(length=50), nullable=True))
    op.add_column("vendors", sa.Column("website", sa.String(length=255), nullable=True))
    op.add_column("vendors", sa.Column("contact_number", sa.String(length=50), nullable=True))
    op.add_column("vendors", sa.Column("email_id", sa.String(length=255), nullable=True))
    op.add_column("vendors", sa.Column("fax", sa.String(length=50), nullable=True))
    op.add_column("vendors", sa.Column("vendor_type", sa.String(length=50), nullable=True))
    op.add_column("vendors", sa.Column("vendor_classification", sa.String(length=50), nullable=True))
    op.add_column("vendors", sa.Column("payment_terms", sa.String(length=50), nullable=True))
    op.add_column("vendors", sa.Column("about_vendor", sa.Text(), nullable=True))
    op.add_column("vendors", sa.Column("address", sa.String(length=500), nullable=True))
    op.add_column("vendors", sa.Column("city", sa.String(length=100), nullable=True))
    op.add_column("vendors", sa.Column("state", sa.String(length=100), nullable=True))
    op.add_column("vendors", sa.Column("country", sa.String(length=100), nullable=True))
    op.add_column("vendors", sa.Column("zip_code", sa.String(length=20), nullable=True))
    op.add_column("vendors", sa.Column("primary_business_unit", sa.String(length=100), nullable=True))
    op.add_column(
        "vendors", sa.Column("business_units", postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'"))
    )
    op.add_column(
        "vendors",
        sa.Column("vendor_visibility", sa.String(length=30), nullable=False, server_default=sa.text("'Organization Level'")),
    )
    op.add_column("vendors", sa.Column("primary_owner_id", sa.UUID(), nullable=True))
    op.add_column("vendors", sa.Column("ownership_id", sa.UUID(), nullable=True))
    op.add_column("vendors", sa.Column("vendor_lead_id", sa.UUID(), nullable=True))
    op.add_column("vendors", sa.Column("send_requirement", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("vendors", sa.Column("send_hotlist", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("vendors", sa.Column("primary_vendor", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column("vendors", sa.Column("allow_access_to_all_users", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column(
        "vendors", sa.Column("technologies", postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'"))
    )
    op.add_column(
        "vendors",
        sa.Column("submission_format_fields", postgresql.ARRAY(sa.String()), nullable=False, server_default=sa.text("'{}'")),
    )
    op.add_column("vendors", sa.Column("submission_instructions", sa.Text(), nullable=True))
    op.add_column("vendors", sa.Column("created_by", sa.UUID(), nullable=True))
    op.add_column("vendors", sa.Column("updated_by", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "vendors", "users", ["ownership_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "vendors", "users", ["updated_by"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "vendors", "users", ["created_by"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "vendors", "users", ["vendor_lead_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "vendors", "users", ["primary_owner_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vendors", type_="foreignkey")
    op.drop_constraint(None, "vendors", type_="foreignkey")
    op.drop_constraint(None, "vendors", type_="foreignkey")
    op.drop_constraint(None, "vendors", type_="foreignkey")
    op.drop_constraint(None, "vendors", type_="foreignkey")
    op.drop_column("vendors", "updated_by")
    op.drop_column("vendors", "created_by")
    op.drop_column("vendors", "submission_instructions")
    op.drop_column("vendors", "submission_format_fields")
    op.drop_column("vendors", "technologies")
    op.drop_column("vendors", "allow_access_to_all_users")
    op.drop_column("vendors", "primary_vendor")
    op.drop_column("vendors", "send_hotlist")
    op.drop_column("vendors", "send_requirement")
    op.drop_column("vendors", "vendor_lead_id")
    op.drop_column("vendors", "ownership_id")
    op.drop_column("vendors", "primary_owner_id")
    op.drop_column("vendors", "vendor_visibility")
    op.drop_column("vendors", "business_units")
    op.drop_column("vendors", "primary_business_unit")
    op.drop_column("vendors", "zip_code")
    op.drop_column("vendors", "country")
    op.drop_column("vendors", "state")
    op.drop_column("vendors", "city")
    op.drop_column("vendors", "address")
    op.drop_column("vendors", "about_vendor")
    op.drop_column("vendors", "payment_terms")
    op.drop_column("vendors", "vendor_classification")
    op.drop_column("vendors", "vendor_type")
    op.drop_column("vendors", "fax")
    op.drop_column("vendors", "email_id")
    op.drop_column("vendors", "contact_number")
    op.drop_column("vendors", "website")
    op.drop_column("vendors", "federal_id")
    op.drop_constraint(None, "vendor_contacts", type_="foreignkey")
    op.drop_column("vendor_contacts", "owner_id")
    op.drop_column("vendor_contacts", "vms_status")
    op.drop_column("vendor_contacts", "status")
    op.drop_column("vendor_contacts", "designation")
    op.drop_column("vendor_contacts", "work_phone")
    op.drop_index(op.f("ix_vendor_meetings_vendor_id"), table_name="vendor_meetings")
    op.drop_table("vendor_meetings")
    op.drop_index(op.f("ix_vendor_notes_vendor_id"), table_name="vendor_notes")
    op.drop_table("vendor_notes")
    op.drop_index(op.f("ix_vendor_documents_vendor_id"), table_name="vendor_documents")
    op.drop_table("vendor_documents")
    op.drop_index(op.f("ix_vendor_bank_accounts_vendor_id"), table_name="vendor_bank_accounts")
    op.drop_table("vendor_bank_accounts")
    op.drop_index(op.f("ix_vendor_accounts_vendor_id"), table_name="vendor_accounts")
    op.drop_table("vendor_accounts")
    # ### end Alembic commands ###
